import { Html, Head, Main, NextScript } from "next/document";

export const metadata = {
    title: "Welcome to Prima's Website",
    description: "Generated by create next app",
};

export default function Document() {
    return (
        <Html>
            <Head>
                <meta name="description" content={metadata.description} />
            </Head>
            <body>
                <Main />
                <NextScript />
            </body>
        </Html>
    );
}
