import { Html, Head, Main, NextScript } from "next/document";

export const metadata = {
    title: "Welcome to Prima's Website",
    description: "Generated by create next app",
};

export default function Document() {
    return (
        <Html>
            <Head>
                <meta name="description" content={metadata.description} />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0, viewport-fit=cover"
                />
                <link
                    rel="stylesheet"
                    href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0"
                />
            </Head>
            <body>
                <Main />
                <NextScript />
            </body>
        </Html>
    );
}
