import Header from "@/components/Header";
import Head from "next/head";
import React from "react";
import "@/styles/globals.css";
import AboutMe from "@/components/AboutMe";

export const metadata = {
    title: "Welcome to Prima's Website",
    description: "Generated by create next app",
};

const Home = () => {
    return (
        <>
            <Head>
                <title>{metadata.title}</title>
                <meta name="description" content={metadata.description} />
                <link
                    rel="stylesheet"
                    href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0"
                />
            </Head>
            <div className="mainLayout">
                <Header />
                <AboutMe />
            </div>
        </>
    );
};

Home.propTypes = {};

export default Home;
